Fix urllib error 😐
For some reason, we cannot just `import urllib`

```
AttributeError: module 'urllib' has no attribute 'error'
```

and have to import `urllib.request` and `urllib.error` explicitly 🤔.
Is this a name-clash with `urllib3` from the bot framework?